config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :movies, only: [ :index ]
  root to: 'lists#index'
  resources :lists, only: [ :show, :new, :create ] do
    resources :bookmarks, only: [ :create, :destroy ]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
  validates :photo, presence: true

end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def create
    @bookmark = Bookmark.new()
    @list = List.find(params[:list_id])
    @bookmark.list_id = @list.id
    @bookmark.comment =  bookmark_params[:comment]
    @bookmark.movie_id = bookmark_params[:movie_id]
    # raise

    if @bookmark.valid?
      @bookmark.save
      redirect_to list_path(@list)
    else
      # raise
      # render :new
      render list: 'lists/show'
    end
  end

  def destroy
    # raise
    @list = List.find(params[:id])
    @bookmark = Bookmark.find(params[:list_id])
    @bookmark.destroy
    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:id, :movie_id, :comment, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    @movies = Movie.all
    # raise
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner background-bottom" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dngfqo2nf/image/upload/v1645307119/production/Stalker2_ly9imk.jpg);">
  <div class="container">
    <h1>Watch lists</h1>
    <p>Movies that you may or may not want to watch</p>
    <%= link_to "Create your own list ...", new_list_path, class: "btn btn-flat" %>
  </div>
</div>

<div class="container mt-4">


  <div class="cards">
    <% @lists.each do |list| %>
      <% url_pic =  cl_image_path list.photo.key %>
      <%= link_to list.name, list_path(list), class: 'card-category', style: "background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(#{url_pic})" %>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://static.fnac-static.com/multimedia/Images/FD/Comete/120558/CCP_IMG_ORIGINAL/1568495.jpg);">
  <div class="container">
    <h1>Watch lists</h1>
    <p>Entrez le nom de votre liste ...</p>
      <%= simple_form_for(@list) do |f| %>
        <%= f.input :name %>
        <%= f.input :photo, as: :file %>
        <%= f.submit 'submit', class: "btn btn-flat" %>
      <% end %>
        <%= link_to "Cancel", root_path, class: "btn btn-flat" %>
  </div>
</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path @list.photo.key, height: 900, corp: :fill  %>);">
  <div class="container">
    <h1><%= @list.name %></h1>
    <p>Add your movies ...</p>
      <%= simple_form_for [@list, @bookmark] do |f| %>
        <%= f.association :movie %>
        <%= f.input :comment %>
        <%= f.submit 'submit', class: "btn btn-flat" %>
        <%= link_to "back home", root_path, class: "btn btn-flat" %>
      <% end %>
  </div>
</div>

<div class="container mt-5 mb-5">
  <% @list.bookmarks.each do |bookmark| %>
    <% pict_url = "https://image.tmdb.org/t/p/w200/#{bookmark.movie.poster_url}" %>
    <% movie_id = bookmark.movie.id %>
    <% list_id = List.find(Bookmark.find(bookmark.id).list_id).id %>
    <div class="card-product mt-3 ">
      <%= image_tag pict_url %>
      <div class="card-product-infos">
        <h2 class='title'><%= bookmark.movie.title %></h2>
        <div class='overview'>
          <p> <%= bookmark.movie.overview %> <br><br></p>
        </div>
        <h6 class='comment'> - "<%= bookmark.comment %> "</h6>
        <%= link_to list_bookmark_path(Bookmark.find(bookmark.id)), method: :delete, data: { confirm: "this article will be deleted, continue ?"} do %>
            <i class="fas fa-trash-alt delete-icon"></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/partials/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>